services:
  app:
    build: .
    container_name: elevatorid_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
    depends_on:
      - mysql
      - redis
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: elevatorid
      MYSQL_USER: elevatorid
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db-data:
