openapi: 3.0.3
info:
  title: ElevatorID API
  version: 1.0.0
  description: >-
    مستند OpenAPI برای سامانه SaaS مدیریت سرویس و نگهداری آسانسور.
servers:
  - url: https://api.example.com
    description: Production
  - url: http://localhost/api
    description: Local
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /v1/auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refresh_token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
security:
  - bearerAuth: []
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
